/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './renderer/routers/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SubIndexLazyImport = createFileRoute('/sub/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./renderer/routers/index.lazy').then((d) => d.Route),
)

const SubIndexLazyRoute = SubIndexLazyImport.update({
  id: '/sub/',
  path: '/sub/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./renderer/routers/sub/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sub/': {
      id: '/sub/'
      path: '/sub'
      fullPath: '/sub'
      preLoaderRoute: typeof SubIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/sub': typeof SubIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/sub': typeof SubIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/sub/': typeof SubIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sub'
  id: '__root__' | '/' | '/sub/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SubIndexLazyRoute: typeof SubIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SubIndexLazyRoute: SubIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sub/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/sub/": {
      "filePath": "sub/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
