name: develop auto pr
on:
  push:
    branches: ["dev"]

jobs:
  pull-request:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: repo-sync/pull-request@v2
        name: pull-request-master
        with:
          destination_branch: "master"
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: "💥 *An automated PR*"
          pr_reviewer: "jl917"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: repo-sync/pull-request@v2
        name: pull-request-master
        with:
          destination_branch: "beta"
          pr_title: "Pulling ${{ github.ref }} into beta"
          pr_body: "💥 *An automated PR*"
          pr_reviewer: "jl917"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
